[package]
name = "noosphere-cli"
version = "0.6.6"
edition = "2021"
description = "Reference client and pedagogical tool to demonstrate the principles of the Noosphere protocol"
keywords = ["cli", "sync", "noosphere", "p2p", "ucan"]
categories = [
  "authentication",
  "filesystem",
  "command-line interface"
]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere-cli"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
test_kubo = []

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
reqwest = { version = "~0.11", default-features = false, features = ["json", "rustls-tls"] }
noosphere-ns = { version = "0.4.3", path = "../noosphere-ns" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tempfile = "^3"
clap = { version = "^4", features = ["derive", "cargo"] }
anyhow = "^1"

tokio = { version = "^1", features = ["full"] }
tokio-stream = "~0.1"
axum = { version = "~0.5", features = ["headers", "macros"] }
tower = "~0.4"
tower-http = { version = "~0.3", features = ["cors", "trace"] }
async-trait = "~0.1"
tracing = "~0.1"
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
multipart = "~0.18"
wnfs = { version = "0.1.9" }
iroh-car = { version = "0.1.3" }

url = { version = "^2", features = [ "serde" ] }
whoami = "^1"
home = "~0.5"
pathdiff = "~0.2"
path-absolutize = "^3"
mime_guess = "^2"
witty-phrase-generator = "~0.2"
toml_edit = { version = "~0.15", features = [ "serde" ] }
globset = "~0.4"

noosphere-ipfs = { version = "0.1.2", path = "../noosphere-ipfs" }
noosphere-core = { version = "0.6.3", path = "../noosphere-core" }
noosphere-sphere = { version = "0.1.0", path = "../noosphere-sphere" }
noosphere-storage = { version = "0.4.2", path = "../noosphere-storage" }
noosphere-api = { version = "0.5.6", path = "../noosphere-api" }
noosphere-gateway = { version = "0.1.0", path = "../noosphere-gateway" }
noosphere = { version = "0.6.3", path = "../noosphere" }
ucan = { version = "0.1.0" }
ucan-key-support = { version = "0.1.0" }
cid = "~0.9"
subtext = "0.3.2"

serde = "^1"
serde_json = "^1"
libipld-core = "~0.15"
libipld-cbor = "~0.15"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "~0.2"
